<<<<<<< HEAD
version: "3.7"
=======
>>>>>>> recuperar-trabajo
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
<<<<<<< HEAD
    image: travellist
    container_name: travellist-app
=======
    image: dawapp
    container_name: dawapp-app
>>>>>>> recuperar-trabajo
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
<<<<<<< HEAD
      - travellist

  db:
    image: mysql:5.7
    container_name: travellist-db
=======
      - dawapp
  
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: dawapp-db
>>>>>>> recuperar-trabajo
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
<<<<<<< HEAD
      - travellist

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
=======
      - dawapp
  
  nginx:
    image: nginx:1.17-alpine
    platform: linux/amd64
    container_name: dawapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
>>>>>>> recuperar-trabajo
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
<<<<<<< HEAD
      - travellist

networks:
  travellist:
    driver: bridge
=======
      - dawapp

networks:
  dawapp:
    driver: bridge
>>>>>>> recuperar-trabajo
